# Generated by Django 5.2.5 on 2025-08-07 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameClass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zavNumberMachine', models.CharField(max_length=20, unique=True)),
                ('zavNumberMotor', models.CharField(max_length=20)),
                ('zavNumberTransmission', models.CharField(max_length=20)),
                ('zavNumberDA', models.CharField(max_length=20)),
                ('zavNumberCA', models.CharField(max_length=20)),
                ('deliveryContract', models.CharField(max_length=50)),
                ('shipDate', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=100)),
                ('deliveryAddress', models.CharField(max_length=150)),
                ('package', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceBook.client')),
                ('modelControllAxile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelControllAxile', to='serviceBook.manual')),
                ('modelDriveAxile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelDriveAxile', to='serviceBook.manual')),
                ('modelMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelMachine', to='serviceBook.manual')),
                ('modelMotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelMotor', to='serviceBook.manual')),
                ('modelTransmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelTransmission', to='serviceBook.manual')),
            ],
        ),
    ]
